/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdSessionRouteImport } from './routes/groups/$groupId/session'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSessionRoute = GroupsGroupIdSessionRouteImport.update({
  id: '/groups/$groupId/session',
  path: '/groups/$groupId/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/watchlist': typeof WatchlistRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/session': typeof GroupsGroupIdSessionRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/watchlist': typeof WatchlistRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId/session': typeof GroupsGroupIdSessionRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/watchlist': typeof WatchlistRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/session': typeof GroupsGroupIdSessionRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/search'
    | '/watch'
    | '/watchlist'
    | '/groups/'
    | '/groups/$groupId/session'
    | '/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/search'
    | '/watch'
    | '/watchlist'
    | '/groups'
    | '/groups/$groupId/session'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/search'
    | '/watch'
    | '/watchlist'
    | '/groups/'
    | '/groups/$groupId/session'
    | '/groups/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  WatchRoute: typeof WatchRoute
  WatchlistRoute: typeof WatchlistRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdSessionRoute: typeof GroupsGroupIdSessionRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/session': {
      id: '/groups/$groupId/session'
      path: '/groups/$groupId/session'
      fullPath: '/groups/$groupId/session'
      preLoaderRoute: typeof GroupsGroupIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  WatchRoute: WatchRoute,
  WatchlistRoute: WatchlistRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdSessionRoute: GroupsGroupIdSessionRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
